# Generated by Django 5.2 on 2025-04-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Miniature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('locomotive', 'Locomotive'), ('passenger_car', 'Passenger Car'), ('freight_car', 'Freight Car'), ('railcar', 'Railcar'), ('other', 'Other')], max_length=50)),
                ('year_of_production', models.CharField(max_length=50)),
                ('era_livery', models.CharField(max_length=100)),
                ('visual_characteristics', models.TextField()),
                ('technical_characteristics', models.TextField()),
                ('article', models.TextField()),
                ('history', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='miniatures/thumbnails/')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='miniatures/main/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='miniatures/qr_codes/')),
            ],
        ),
    ]
