# Generated by Django 5.2 on 2025-04-29 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniatures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='miniatures/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('miniature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='miniatures.miniature')),
            ],
            options={
                'verbose_name_plural': 'Gallery images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
